### ISSUE TITLE
License selection

### ISSUE THREAD

**Issue by atombaby** [FredHutch/sti_crc_method_comparison#2]
This is currently a public repository (we default to keeping these things public unless we have a good reason to make it private).  Secrets we store elsewhere.

Anyway, we should put some sort of license on this cookbook in case someone wants to fork it or use some of the techniques.  I like Apache 2.0- @nhoffman do you have a license you like?

**Comment by nhoffman** [comment]
I generally default to MIT for stuff that I just want to throw into the public domain (based on the recommendation of some tech transfer folks at one point), but honestly I couldn't tell you how MIT differs from Apache.
