### ISSUE TITLE
Protocol selection

### ISSUE THREAD

**Issue by atombaby** [FredHutch/sti_crc_method_comparison#3]
Right now (I think) we think the two viable options are sftp and webdav.  I think this choice largely separate from the environment its run in, but I'm still waiting to hear about the AWS options available to us.  I've written up how either WebDAV or sftp might work [here](https://github.com/FredHutch/friendly-succotash/blob/dev/README.md)

Personally, I still think webdav is likely the better solution simply because of the variety of client options.  However, your point about adding things to other IT environments and the availability of tools therein is well taken.  

Given that, I'd say an sftp server running on an alternate address is the next best way to implement this.  It'd be something like "sftphost.fhcrc.org" for those using the service (sftp) and "sftphost-admin.fhcrc.org" for those of us using ssh for login/admin/management purposes.

**Comment by nhoffman** [comment]
@atombaby - Thanks a lot for providing this resource. I think that the choice of protocol will depend on who will have the responsibility of supporting the collaborating sites. I'm pretty confident I can provide instructions for sftp access from either a desktop or a headless server, and sftp access from the command line is a known quantity. If the scientific computing facility is willing to provide instructions and support for webdav, then that could work as well.

**Comment by atombaby** [comment]
The further thought occurs that I don't think using one protocol makes the other unworkable, meaning maybe we can run both.  Assuming we can get the appropriate OKs on admitting traffic through the firewall, that is.

I've done some work getting sftp set up (check the branch `mrg/sftp-server`)... it seems viable.  I'm going to focus on that for the time being.

**Comment by nhoffman** [comment]
The thought of running both has occurred to me as well, but I don't want to make this more complicated than it has to me, unless you anticipate using it for other users and projects.

**Comment by atombaby** [comment]
Yep- I figure I'd focus on sftp for now, add another protocol if it becomes
a requirement.  More just noting that it isn't an either/or question.

I'm going to close #3 out.  If we want to change or add additional
protocols we'll do those as their own issue down the road.

M
